// ═══════════════════════════════════════════════════════════════════════════════
// NEW FILE: WorldExplorer/JetBlackEngineLib/Data/Executable/BgdaExecutable.ThreePlayer.cs
//
// Three-player co-op for SLES_506.72 (PAL): Adrianna the Elven Sorceress joins as
// player 3 through a "Three Player" entry in the main menu. One- and two-player
// games run the stock code.
//
// The patch is the exact difference between the stock executable and the tested
// ADRIANNA19 build (see BgdaExecutablePatches.cs, generated by
// make_worldexplorer_patch.py from the three-player tools). Turning it on checks that every byte it
// replaces is still the stock byte, writes the patched bytes and appends the
// staged code (the file grows from 2,274,512 to 5,235,712 bytes). Turning it off
// checks the patch is intact and writes the stock bytes back, so a stock file
// round-trips exactly. Edits made by the other tabs (XP, stats, feats, monster HP,
// difficulty scaling) are in places the patch never touches and survive both ways.
//
// SETTINGS (only while three players are on; all apply to three-player games only)
//   BAL3 balance table  file 0x4FB000: monster HP, damage die, XP value, boss HP,
//                       gold per drop, item chance, gold chance, Orb of Undeath divisor
//   map markers         file 0x4FC180: one GS RGBA colour per player
//   small map           file 0x4FC108 (x, y) / 0x4FC120 (width, height)
// ═══════════════════════════════════════════════════════════════════════════════
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace JetBlackEngineLib.Data.Executable;

public enum ThreePlayerState
{
    /// <summary>The stock executable: the patch can be turned on.</summary>
    Off,
    /// <summary>The three-player patch is present and intact: settings can be edited.</summary>
    On,
    /// <summary>Neither: another build or other changes where the patch lives.</summary>
    Unrecognized
}

/// <summary>An 8-bit RGB colour (automap marker).</summary>
public readonly record struct Rgb(int R, int G, int B);

/// <summary>Three-player settings stored in the patched executable.</summary>
public sealed class ThreePlayerSettings
{
    // ---- balance (BAL3); two players use 1.7 / 1.4 / 2 / 1.7 / 2 / 2 / 1.5 / 2 ----
    public float MonsterHp { get; set; }
    public float MonsterDamage { get; set; }
    public float XpValue { get; set; }
    public float BossHp { get; set; }
    public float GoldPerDrop { get; set; }
    public float ItemChance { get; set; }
    public float GoldChance { get; set; }
    /// <summary>Orb of Undeath: damage is divided by this (two players: 2).</summary>
    public int OrbDivisor { get; set; }

    /// <summary>Automap marker colour of players 1, 2 and 3.</summary>
    public Rgb[] Markers { get; set; } = new Rgb[3];

    // ---- small automap with three players (offset from the screen centre; +y is down) ----
    public float SmallMapX { get; set; }
    public float SmallMapY { get; set; }
    public float SmallMapWidth { get; set; }
    public float SmallMapHeight { get; set; }
}

public partial class BgdaExecutable
{
    public const float MinThreePlayerFactor = 0.01f;
    public const float MaxThreePlayerFactor = 100f;
    public const int MinOrbDivisor = 1, MaxOrbDivisor = 10;
    public const float MaxSmallMapOffset = 320f, MinSmallMapSize = 1f, MaxSmallMapSize = 640f;

    /// <summary>File length of the stock executable and of the three-player one.</summary>
    public const int StockFileLength = ThreePlayerPatch.StockLength;
    public const int ThreePlayerFileLength = ThreePlayerPatch.PatchedLength;

    /// <summary>Numbers in messages always use '.', matching what the editor accepts.</summary>
    private static string Inv(float v) => v.ToString(CultureInfo.InvariantCulture);

    private const uint MarkerAlpha = 0x80000000u;   // GS RGBA: alpha 0x80 = opaque

    // ---- patch data (decoded once, verified against its SHA-256) ----

    private sealed record PatchRun(int Offset, byte[] Stock, byte[] Patched);
    private sealed record TailRun(int Offset, byte[] Bytes);

    private static readonly Lazy<(PatchRun[] Runs, TailRun[] Tail)> Patch = new(LoadPatch);

    private static (PatchRun[] Runs, TailRun[] Tail) LoadPatch()
    {
        var blob = Convert.FromBase64String(ThreePlayerPatch.BlobBase64);
        var hash = Convert.ToHexString(SHA256.HashData(blob)).ToLowerInvariant();
        if (hash != ThreePlayerPatch.BlobSha256)
            throw new InvalidDataException("The built-in three-player patch data is damaged.");

        var pos = 0;
        int U32()
        {
            var v = BitConverter.ToInt32(blob, pos);
            pos += 4;
            return v;
        }
        byte[] Bytes(int n)
        {
            var b = new byte[n];
            Array.Copy(blob, pos, b, 0, n);
            pos += n;
            return b;
        }

        if (Encoding.ASCII.GetString(blob, 0, 4) != "3PL1")
            throw new InvalidDataException("Unknown three-player patch format.");
        pos = 4;
        if (U32() != ThreePlayerPatch.StockLength || U32() != ThreePlayerPatch.PatchedLength)
            throw new InvalidDataException("Three-player patch lengths do not match.");

        var runs = new PatchRun[U32()];
        for (var i = 0; i < runs.Length; i++)
        {
            var off = U32();
            var len = U32();
            runs[i] = new PatchRun(off, Bytes(len), Bytes(len));
        }

        var tail = new TailRun[U32()];
        for (var i = 0; i < tail.Length; i++)
        {
            var off = U32();
            var len = U32();
            tail[i] = new TailRun(off, Bytes(len));
        }

        if (pos != blob.Length)
            throw new InvalidDataException("Three-player patch data has trailing bytes.");
        return (runs, tail);
    }

    // ---- state ----

    /// <summary>
    /// Off = stock, On = the three-player patch is intact, Unrecognized = anything
    /// else (an older three-player build, or other changes where the patch lives).
    /// <paramref name="detail"/> explains the verdict in a sentence.
    /// </summary>
    public ThreePlayerState GetThreePlayerState(out string detail)
    {
        var (runs, tail) = Patch.Value;

        if (_data.Length == ThreePlayerPatch.StockLength)
        {
            var bad = FirstMismatch(runs, stock: true);
            if (bad < 0)
            {
                detail = "Stock executable: three players can be turned on.";
                return ThreePlayerState.Off;
            }

            detail = $"The executable has the stock length, but {CountMismatches(runs, true)} of " +
                     $"{runs.Length} places the three-player patch changes are already different " +
                     $"(first at file offset 0x{bad:X6}). It may hold another patch, so the switch is off-limits.";
            return ThreePlayerState.Unrecognized;
        }

        if (_data.Length == ThreePlayerPatch.PatchedLength)
        {
            var bad = FirstMismatch(runs, stock: false);
            var badTail = FirstTailMismatch(tail);
            if (bad < 0 && badTail < 0 && HasBal3Header())
            {
                detail = "Three players are on (the tested ADRIANNA19 patch).";
                return ThreePlayerState.On;
            }

            var where = bad >= 0 ? bad : badTail;
            detail = "The executable has the three-player length but is not the tested ADRIANNA19 " +
                     $"build (first difference at file offset 0x{where:X6}) - for example an older " +
                     "three-player build. Open the stock SLES_506.72 or an ADRIANNA19 build.";
            return ThreePlayerState.Unrecognized;
        }

        detail = $"The executable is {_data.Length:N0} bytes; the stock one is " +
                 $"{ThreePlayerPatch.StockLength:N0} and the three-player one " +
                 $"{ThreePlayerPatch.PatchedLength:N0}, so the switch is off-limits.";
        return ThreePlayerState.Unrecognized;
    }

    public ThreePlayerState GetThreePlayerState() => GetThreePlayerState(out _);

    private int FirstMismatch(PatchRun[] runs, bool stock)
    {
        foreach (var r in runs)
        {
            var want = stock ? r.Stock : r.Patched;
            for (var i = 0; i < want.Length; i++)
            {
                if (_data[r.Offset + i] != want[i]) return r.Offset + i;
            }
        }

        return -1;
    }

    private int CountMismatches(PatchRun[] runs, bool stock)
    {
        var n = 0;
        foreach (var r in runs)
        {
            var want = stock ? r.Stock : r.Patched;
            for (var i = 0; i < want.Length; i++)
            {
                if (_data[r.Offset + i] != want[i]) { n++; break; }
            }
        }

        return n;
    }

    private int FirstTailMismatch(TailRun[] tail)
    {
        foreach (var t in tail)
        {
            for (var i = 0; i < t.Bytes.Length; i++)
            {
                var off = t.Offset + i;
                if (IsEditable(off)) continue;
                if (_data[off] != t.Bytes[i]) return off;
            }
        }

        return -1;
    }

    private static bool IsEditable(int offset)
    {
        foreach (var (o, n) in ThreePlayerPatch.EditableRanges)
        {
            if (offset >= o && offset < o + n) return true;
        }

        return false;
    }

    private bool HasBal3Header() =>
        _data[ThreePlayerPatch.Bal3Offset] == (byte)'B' &&
        _data[ThreePlayerPatch.Bal3Offset + 1] == (byte)'A' &&
        _data[ThreePlayerPatch.Bal3Offset + 2] == (byte)'L' &&
        _data[ThreePlayerPatch.Bal3Offset + 3] == (byte)'3' &&
        BitConverter.ToInt32(_data, ThreePlayerPatch.Bal3Offset + 4) == 1;

    // ---- on / off ----

    /// <summary>
    /// Applies the three-player patch to a stock executable (state must be Off).
    /// Nothing is changed if the check fails.
    /// </summary>
    public void EnableThreePlayers()
    {
        if (GetThreePlayerState(out var detail) != ThreePlayerState.Off)
            throw new InvalidOperationException("Three players cannot be turned on: " + detail);

        var (runs, tail) = Patch.Value;
        var data = new byte[ThreePlayerPatch.PatchedLength];
        Array.Copy(_data, data, _data.Length);
        foreach (var r in runs) Array.Copy(r.Patched, 0, data, r.Offset, r.Patched.Length);
        foreach (var t in tail) Array.Copy(t.Bytes, 0, data, t.Offset, t.Bytes.Length);
        _data = data;
    }

    /// <summary>
    /// Removes the three-player patch (state must be On): the stock bytes are written
    /// back and the file returns to its stock length. Three-player settings are lost.
    /// </summary>
    public void DisableThreePlayers()
    {
        if (GetThreePlayerState(out var detail) != ThreePlayerState.On)
            throw new InvalidOperationException("Three players cannot be turned off: " + detail);

        var (runs, _) = Patch.Value;
        var data = new byte[ThreePlayerPatch.StockLength];
        Array.Copy(_data, data, data.Length);
        foreach (var r in runs) Array.Copy(r.Stock, 0, data, r.Offset, r.Stock.Length);
        _data = data;
    }

    // ---- settings ----

    /// <summary>The settings as the patch ships them (the ADRIANNA19 values).</summary>
    public static ThreePlayerSettings DefaultThreePlayerSettings()
    {
        var image = new Dictionary<int, byte>();
        foreach (var t in Patch.Value.Tail)
        {
            for (var i = 0; i < t.Bytes.Length; i++) image[t.Offset + i] = t.Bytes[i];
        }

        byte At(int off) => image.TryGetValue(off, out var b) ? b : (byte)0;
        byte[] Read(int off, int n)
        {
            var b = new byte[n];
            for (var i = 0; i < n; i++) b[i] = At(off + i);
            return b;
        }

        return ReadSettings(Read);
    }

    /// <summary>Reads the three-player settings (state must be On).</summary>
    public ThreePlayerSettings GetThreePlayerSettings()
    {
        RequireOn();
        return ReadSettings((off, n) =>
        {
            var b = new byte[n];
            Array.Copy(_data, off, b, 0, n);
            return b;
        });
    }

    private static ThreePlayerSettings ReadSettings(Func<int, int, byte[]> read)
    {
        var bal = read(ThreePlayerPatch.Bal3Offset, 0x28);
        float F(byte[] b, int at) => BitConverter.ToSingle(b, at);

        var markers = read(ThreePlayerPatch.MarkerOffset, 12);
        var pos = read(ThreePlayerPatch.SmallMapPosition, 8);
        var size = read(ThreePlayerPatch.SmallMapSize, 8);

        var s = new ThreePlayerSettings
        {
            MonsterHp      = F(bal, 0x08),
            MonsterDamage  = F(bal, 0x0C),
            XpValue        = F(bal, 0x10),
            BossHp         = F(bal, 0x14),
            GoldPerDrop    = F(bal, 0x18),
            ItemChance     = F(bal, 0x1C),
            GoldChance     = F(bal, 0x20),
            OrbDivisor     = BitConverter.ToInt32(bal, 0x24),
            SmallMapX      = F(pos, 0),
            SmallMapY      = F(pos, 4),
            SmallMapWidth  = F(size, 0),
            SmallMapHeight = F(size, 4)
        };
        for (var p = 0; p < 3; p++)
        {
            var w = BitConverter.ToUInt32(markers, p * 4);
            s.Markers[p] = new Rgb((int)(w & 0xFF), (int)((w >> 8) & 0xFF), (int)((w >> 16) & 0xFF));
        }

        return s;
    }

    /// <summary>
    /// Writes the three-player settings (state must be On). Every value is checked
    /// first; nothing is written if any is out of range.
    /// </summary>
    public void SetThreePlayerSettings(ThreePlayerSettings s)
    {
        RequireOn();
        ValidateThreePlayerSettings(s);

        var b = ThreePlayerPatch.Bal3Offset;
        WriteFloat(b + 0x08, s.MonsterHp);
        WriteFloat(b + 0x0C, s.MonsterDamage);
        WriteFloat(b + 0x10, s.XpValue);
        WriteFloat(b + 0x14, s.BossHp);
        WriteFloat(b + 0x18, s.GoldPerDrop);
        WriteFloat(b + 0x1C, s.ItemChance);
        WriteFloat(b + 0x20, s.GoldChance);
        WriteInt(b + 0x24, s.OrbDivisor);

        for (var p = 0; p < 3; p++)
        {
            var c = s.Markers[p];
            var w = MarkerAlpha | (uint)c.R | ((uint)c.G << 8) | ((uint)c.B << 16);
            BitConverter.GetBytes(w).CopyTo(_data, ThreePlayerPatch.MarkerOffset + p * 4);
        }

        WriteFloat(ThreePlayerPatch.SmallMapPosition, s.SmallMapX);
        WriteFloat(ThreePlayerPatch.SmallMapPosition + 4, s.SmallMapY);
        WriteFloat(ThreePlayerPatch.SmallMapSize, s.SmallMapWidth);
        WriteFloat(ThreePlayerPatch.SmallMapSize + 4, s.SmallMapHeight);
    }

    /// <summary>Throws <see cref="ArgumentException"/> naming the first bad value.</summary>
    public static void ValidateThreePlayerSettings(ThreePlayerSettings s)
    {
        void Factor(string name, float v)
        {
            if (float.IsNaN(v) || v < MinThreePlayerFactor || v > MaxThreePlayerFactor)
                throw new ArgumentException(
                    $"Three-player {name} must be between {Inv(MinThreePlayerFactor)} and {Inv(MaxThreePlayerFactor)}.");
        }

        Factor("monster HP", s.MonsterHp);
        Factor("monster damage", s.MonsterDamage);
        Factor("XP value", s.XpValue);
        Factor("boss HP", s.BossHp);
        Factor("gold per drop", s.GoldPerDrop);
        Factor("item drop chance", s.ItemChance);
        Factor("gold drop chance", s.GoldChance);
        if (s.OrbDivisor < MinOrbDivisor || s.OrbDivisor > MaxOrbDivisor)
            throw new ArgumentException(
                $"The Orb of Undeath divisor must be a whole number from {MinOrbDivisor} to {MaxOrbDivisor}.");

        if (s.Markers is null || s.Markers.Length != 3)
            throw new ArgumentException("Three marker colours are needed.");
        for (var p = 0; p < 3; p++)
        {
            var c = s.Markers[p];
            if (c.R is < 0 or > 255 || c.G is < 0 or > 255 || c.B is < 0 or > 255)
                throw new ArgumentException($"Player {p + 1} marker colour channels must be between 0 and 255.");
        }

        void Range(string name, float v, float lo, float hi)
        {
            if (float.IsNaN(v) || v < lo || v > hi)
                throw new ArgumentException($"Small-map {name} must be between {Inv(lo)} and {Inv(hi)}.");
        }

        Range("x", s.SmallMapX, -MaxSmallMapOffset, MaxSmallMapOffset);
        Range("y", s.SmallMapY, -MaxSmallMapOffset, MaxSmallMapOffset);
        Range("width", s.SmallMapWidth, MinSmallMapSize, MaxSmallMapSize);
        Range("height", s.SmallMapHeight, MinSmallMapSize, MaxSmallMapSize);
    }

    private void RequireOn()
    {
        if (GetThreePlayerState(out var detail) != ThreePlayerState.On)
            throw new InvalidOperationException("Three-player settings are not available: " + detail);
    }

    private void WriteFloat(int off, float value) => BitConverter.GetBytes(value).CopyTo(_data, off);
}
